//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videoclub.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler
    {
        public int idAlquiler { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<double> TotalPagar { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
