//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videoclub.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula : articulo
    {
        public Nullable<int> Duracion { get; set; }
        public Nullable<int> NumeroDvd { get; set; }
        public Nullable<int> AnioPublicacion { get; set; }
        public Nullable<int> AnioCompra { get; set; }
    }
}
