//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videoclub.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoJuego : articulo
    {
        public Nullable<int> NumeroDiscos { get; set; }
        public string Plataforma { get; set; }
    }
}
